### ISSUE TITLE
taskを取得するエンドポイントを追加・実装する

### ISSUE THREAD

**Issue by Shuri-Honda-1101** [Shuri-Honda-1101/todo-go#15]
# 概要

DB に追加されている全ての task を取得するエンドポイントを追加・ルーティング設定・ハンドラー関数の実装を行う

尚、今回は関数や go のコードを１から書いてもらう。
そのため、**Progate の Go のコースは全て修了している状態がおすすめ。**

今回目指すのは、
「全然理解できてないけど、他のコードパクりながら書いたらなんか動いた！」
という状態

# 目的

- Go で関数を書けるようになる
- Go でエンドポイントを設定できるようになる
- Go でルーティング設定ができるようになる

# タスク

- [x] 今回作成するエンドポイントについて理解しよう
- [x] いつものgitの流れをやっとこう
- [x] ハンドラー関数の雛形を書いてみよう
- [x] ルーティングを設定してみよう
- [x] ルーティング設定を curl で確認してみよう
- [x] SQL 文を書いてみよう
- [x] DB から task 全ての行データ(rows)をクエリしてこよう
- [x] DB から受け取った rows を１つずつ Task 構造体に詰め替えよう
- [x] Task 構造体のsliceを JSON 形式でクライアントに返してみよう
- [x] エラーハンドリングを実装してみよう
- [x] curl で実装したエンドポイントの動作を確認しよう
- [x] フロントエンドから確認してみよう
- [x] PR を出そう
- [x] レビューを元にリファクタリングをしよう
- [x] approve されたらマージしよう

# 具体的な手順

### 要件
今回作成するのは以下の要件を満たしたエンドポイント

- データベースから全てのTaskデータを取得
- JSON形式でクライアントに返す
- エンドポイントは`/tasks`とする

### Question
さて、この場合、HTTPメソッドは何を使うのが適切か考えてみよう( GET / POST / PUT / PATCH / DELETE )
<details><summary>回答</summary>
<p>

「取得」なので<b>GET</b>メソッドとなる

</p>
</details> 

## いつものgitの流れをやっとこう

詳細な説明は割愛するが、いつも通り以下の流れを行う

### 流れ
- mainブランチに移動する
- pullして最新のmainブランチを取り込む
- 作業ブランチを切る

## ハンドラー関数の雛形を書いてみよう

ハンドラー関数の雛形を書こう。(つまり、機能は実装しなくて良い)

### 要件
- `echo.Context`と`*sql.DB`を引数にとる
- 関数名は`getTasks`とする
- StatusOKとJSONを返す
  -  JSONはまだ無いので`get Task!`という文字列を設定する

### 参考にするコード
既存のコードでハンドラー関数を書いているのは以下の部分なので参考にしよう

https://github.com/Shuri-Honda-1101/todo-go/blob/6d10ee92ac34694d2b30dda6723ce5ad61ba6c41/server/server.go#L61-L64

https://github.com/Shuri-Honda-1101/todo-go/blob/6d10ee92ac34694d2b30dda6723ce5ad61ba6c41/server/server.go#L80-L117

## エンドポイントを作ってみよう

echoフレームワークの機能を使ってエンドポイントを作ってみよう。

### 要件
- GETメソッド
- エンドポイントは`/tasks`
- 関数呼び出しまでは行わなくて良い(`GET`メソッドの第二引数はまだ書かなくて良い)

### 参考にするコード
既存のコードではこの部分でエンドポイント(とルーティング)を設定している。
https://github.com/Shuri-Honda-1101/todo-go/blob/6d10ee92ac34694d2b30dda6723ce5ad61ba6c41/server/server.go#L51-L55

## ルーティングを設定してみよう

さて、ここまででハンドラー関数とエンドポイントを作成できた。
今回はこの２つを繋いでルーティングを設定しよう。

とは言っても、すでに雛形は完成しているので、エンドポイントの`GET`メソッドの第二引数に、`getTasks`関数を設定すれば良い。

### 参考にするコード
https://github.com/Shuri-Honda-1101/todo-go/blob/6d10ee92ac34694d2b30dda6723ce5ad61ba6c41/server/server.go#L53-L55

## ルーティング設定を curl で確認してみよう

ここまでで
ハンドラー関数
エンドポイント
ルーティング
が設定できた。

つまり、
`/tasks`というエンドポイントに対してGETメソッドを叩けばハンドラー関数が実行される
という状況になっているはず。

実際にcurlコマンドで確認してみよう。

### コマンド
以下のコマンドを叩く。
```sh
$ curl -X GET http://localhost:1323/tasks
```

### 結果
`"get Task!"`
という文字列が返ってきているはず。

## SQL 文を書いてみよう
ハンドラー関数の中身を実装していこう。

### Question
まず、tasksテーブルの全てのデータを取得してくるSQL文を考えてみよう。

<details><summary>回答</summary>
<p>

```sql
mysql > SELECT * FROM tasks;
```

</p>
</details>

### 要件
では、実際にハンドラー関数にこのSQL文を書いていこう。

今までの実装を見てみると、
SQL文を格納する変数を定義して、変数に文字列としてSQL文を代入していることが分かるね。
https://github.com/Shuri-Honda-1101/todo-go/blob/6d10ee92ac34694d2b30dda6723ce5ad61ba6c41/server/server.go#L108

今回の要件は以下の通り
- `getTasks`関数の中に実装する
- `sqlSelect`という変数にSQL文を格納する
- 実際にDBから取得してくるコードは書かなくて良い

### 参考にするコード

https://github.com/Shuri-Honda-1101/todo-go/blob/6d10ee92ac34694d2b30dda6723ce5ad61ba6c41/server/server.go#L80-L117

## DB から task 全ての行データ(rows)をクエリしてこよう

それでは、さっき作成したSQL文を実際に実行するようにDBに命令するコードを書こう。

前回のタスクで読んだ以下の記事を思い出そう
https://www.twihike.dev/docs/golang-database/queries

> クエリ対象のレコード数が決まっていない場合はDB.Queryメソッドを使います。

前回のタスクではID指定で１つのtaskレコード(データ)を取得している。
https://github.com/Shuri-Honda-1101/todo-go/blob/6d10ee92ac34694d2b30dda6723ce5ad61ba6c41/server/server.go#L109
この時は1行だけなので`QueryRow`メソッドを使っていた。
が、今回は複数のレコードを取得してくるので、`Query`メソッドを使用する。

### 要件
- `db.Query`メソッドでSQL文を実行する
- `db.Query`メソッドには`sqlSelect`変数を渡す
- エラーハンドリングを行う
- エラーが発生した際は、`slog.Error("Fail to retrieve task", "error", err)`でログを出力し、エラーを返す
- `defer`で関数の終了時に取得してきた行データをクローズする。`rows.Close()` 

<details><summary>rows.Closeってなに？</summary>
<p>

コネクションを占領し続けるから〜という理由があるのだが、もうこれは呪文のように思っておいてもらえればいい。　Queryメソッドを使ったらCloseまでセット

https://blog.nownabe.com/2017/01/16/570.html/#fetching-data-from-the-database

</p>
</details> 

### 参考にするコード
https://github.com/Shuri-Honda-1101/todo-go/blob/6d10ee92ac34694d2b30dda6723ce5ad61ba6c41/server/server.go#L109-L113

記事も参考にすると良い。
[SQLの実行方法（NレコードのSELECT）](https://www.twihike.dev/docs/golang-database/queries#sql%E3%81%AE%E5%AE%9F%E8%A1%8C%E6%96%B9%E6%B3%95%EF%BC%88n%E3%83%AC%E3%82%B3%E3%83%BC%E3%83%89%E3%81%AEselect%EF%BC%89)

### rows.Nextしよう
再度下記の記事を確認しよう。
https://www.twihike.dev/docs/golang-database/queries#sql%E3%81%AE%E5%AE%9F%E8%A1%8C%E6%96%B9%E6%B3%95%EF%BC%88n%E3%83%AC%E3%82%B3%E3%83%BC%E3%83%89%E3%81%AEselect%EF%BC%89

> Rows.Nextメソッドで取得できるレコードがあることを確認
> Rows.Scanメソッドでレコードを取得

となっている。

`rows.Scan`で実際に取得してきたレコードを読み込むことができるのだが、その前段階の準備として`rows.Next`をする必要がある。
`rows.Next`はエラーが発生した場合か、次のレコードがない場合に`false`を返す。

つまり、仮に３つ該当するtaskレコードがあったとして、

1. rows.Next()で１つ目のレコードを取得する準備をする。レコードがあるので結果はtrue。
2. rows.Next()で２つ目のレコードを取得する準備をする。レコードがあるので結果はtrue。
3. rows.Next()で３つ目のレコードを取得する準備をする。レコードがあるので結果はtrue。
4. rows.Next()で４つ目のレコードを取得する準備をする。**レコードがないので結果はfalse。**

となる。

しかし、今は何個該当するレコードがあるか分からない。
分からないので、rows.Next()を何回もベタ書きすることができない。
分からないときは繰り返し処理をするしかない。
繰り返し処理って何を使うんだっけ…？？？？？

**-> for文**

というわけで、for文を使って繰り返し処理を行なっていく。
for文は、評価対象がfalseとなるまで処理を繰り返し実行する。
例えば、3回繰り返し処理を実行したいときは、「iが0から始まって、iが3未満の時」を評価文とする。
具体的には以下のような感じ

```go
for i := 0; i < 3; i++ {
	fmt.Println(i)
}
```

`i := 0; i < 3; i++`という部分が評価文だね。

#### Question
じゃあ、今回は何がfalseになった時に処理をやめたいんだっけ？
for文の雛形を考えてみよう。

<details><summary>回答</summary>
<p>

`rows.Next()`がfalseになった時に処理をやめたい。
つまり、評価文にはrows.Next()を設定すれば良い。

```go
for rows.Next() {
    fmt.Println("rows.Next()がtrueだったよ")
}
```

</p>
</details> 

### rows.Scanしよう
これで取得してきた全てのレコードを順番に読み込む準備ができた。
実際に読み込むには`rows.Scan()`で読み込んで、task構造体にデータを入れ込んであげる必要がある。

#### 要件
for文の中でやることは以下の通り
- task構造体を定義する
- rows.Scanでtask構造体に値を入れていく
- エラーが起きたらハンドリングする

#### 参考にするコード
https://github.com/Shuri-Honda-1101/todo-go/blob/6d10ee92ac34694d2b30dda6723ce5ad61ba6c41/server/server.go#L105-L113

### taskをsliceに詰めていこう
さて、さっきの段階でfor文の中で取得してきたデータをtask構造体に詰め替えることができた。
が、これはfor文のループ1回おきにtask構造体が無かったことになってしまう。
実際は全てのtaskが欲しいので、全てのtaskを格納する`tasks`というsliceを作成し、sliceにtaskを詰めてあげる必要がある。

#### 要件
- for文の外で`tasks`という`task`構造体のsliceを定義する
- for文の中で`tasks`に`task`を詰め込んでいく

#### 解答
<details><summary>解答</summary>
<p>

```go
var tasks []Task // ここでtasksを定義

for rows.Next() {
	var task Task
	err = rows.Scan(&task.ID, &task.Text, &task.CompletedAt, &task.DeletedAt, &task.CreatedAt, &task.UpdatedAt)
	if err != nil {
		slog.Error("Fail to scan task", "error", err)
		return err
	}
	tasks = append(tasks, task) // ここでtasksにtaskを詰め込む
}
```

</p>
</details> 

## Task 構造体のsliceを JSON 形式でクライアントに返してみよう

前回まででtasksというsliceにDBの全てのタスクのデータを詰め込むことができたはず。
今回はこれをクライアントにJSONで返却しよう。
と言っても、すでにJSONを返却する雛形は出来ているはず。
文字列を返していた部分を、tasksに変えれば良いだけ。

### 要件
- `tasks`をJSONで返却する

### 参考にするコード
https://github.com/Shuri-Honda-1101/todo-go/blob/6d10ee92ac34694d2b30dda6723ce5ad61ba6c41/server/server.go#L116

## エラーハンドリングを実装してみよう
今まで何度も
```go
if err != nil {
　slog.Error("なんか文字列", "error", err)
　return err
}
```
というコードを書いてきたと思う。

これがgoで基本となるエラーハンドリングだ。
errを返ってくる可能性がある関数を呼び出す時は基本的に`if err != nil { ... }`を行う。
これはもう呪文だと思って欲しい。 
これをやらないと、エラーが発生した時に「なんかよくわかんないけどプログラムが正常終了しなかった」みたいな感じになる。
ちなみに上記で行っていることは、
「エラーが発生したら、エラーのログを出して、関数はエラーを返却してね」
ということ。
`slog.Error(....)`の部分がエラーログの出力部分だ。
「なんか文字列」と書いている部分は、その時々に合った文字列を書いておく。
例えば、
- 「taskレコードのスキャンに失敗した」 -> 「Fail to scan task」
- 「データベースからの読み取りに失敗した」 -> 「Fail to read from the database」
のような感じ。
(プロジェクトによって日本語を使うか英語を使うかは異なる)

さて、`rows.Next()`を書いた部分に着目してみよう。
`rows.Next()`はエラーを返さないので、エラーハンドリングを行なっていない。
が、実際にはエラーが発生する可能性がある。(DBからのデータの読み取り中に問題が発生した場合など)
では、ここで発生したエラーはどうやってハンドリングするのか？
実は`rows.Err()`でループ処理中に発生したエラーを確認することができる。
そのため、for文のループが終わった後に、`rows.Err()`を呼び出すことで、エラーハンドリングが可能になる。

`rows.Err()`はエラーを返すので、
```go
err = rows.Err()
```
とすれば良い。
errがあるということは…？
この先を書いてみよう。

### 要件
- for文のループ外で`rows.Err()`を使って、ループ中のエラーを補足する
- エラーが発生したらログを出す
- エラーが発生したら関数はエラーを返却する

### 解答
<details><summary>解答</summary>
<p>

```go
err = rows.Err()
if err != nil {
	slog.Error("Fail to read from the database", "error", err)
	return err
}
```

</p>
</details> 

## curl で実装したエンドポイントの動作を確認しよう
これでtask取得のエンドポイント実装が完了した。

実際にまたcurlを叩いて動作を確認してみよう。

### コマンド
以下のコマンドを叩く。
```sh
$ curl -X GET http://localhost:1323/tasks
```

### 結果
こんな感じでデータが返ってくるはず。
<img width="630" alt="スクリーンショット 2024-08-24 7 53 40" src="https://github.com/user-attachments/assets/c4854cea-d1e1-4598-a6e3-4e74c972fdda">

### 手順
- サーバーを起動させる(もう起動してたらok)
- 別のターミナルでフロントエンドを起動させる(`client`ディレクトリで`npm run dev`)
- `localhost:3000`にアクセスする

### 結果
こんな感じで、タスクが表示されるようになる。
<img width="300" alt="スクリーンショット 2024-08-24 7 53 40" src="https://github.com/user-attachments/assets/9d89bb54-97b5-4189-a5b3-7f2527df6cef">

また、タスクを追加した際も、ちゃんと追加分が表示される

## PR を出そう
いつも通り

## レビューを元にリファクタリングをしよう
いつも通り

## approve されたらマージしよう
いつも通り

# その他
